apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs
  name: nodejs
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
    - port: 3000           
      targetPort: 3000     
      protocol: TCP
