apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs19
  name: nodejs19
spec:
  type: NodePort
  selector:
    app: nodejs19
  ports:
    - port: 3000           
      targetPort: 3000     
      protocol: TCP
